version: "3"
services:
  telegram-alerts:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8000:8000
    depends_on:
      - db
  db:
    image: mysql:8
    platform: linux/amd64
    ports:
      - 3306:3306
    environment:
      MYSQL_DATABASE: telegram_alerts
      MYSQL_ROOT_PASSWORD: 12345
      # MYSQL_TCP_PORT: 3306
