version: "3"
services:
  checking-token:
    build:
      context: ./
      dockerfile: ./Dockerfile
    ports:
      - 8000:8000
    depends_on:
      - db
  db:
    image: mysql:5.7
    platform: linux/amd64
    ports:
      - 3306:3306
    environment:
      MYSQL_DATABASE: checking_token
      MYSQL_ROOT_PASSWORD: 12345
      # MYSQL_TCP_PORT: 3306
